Repository amtsu/team22, pull requests merged in 2024-03, with the labels that each got.

#451 выполнила множество и словари
  users/rmarfenkova/exercise/hw5/Untitled.ipynb
  users/rmarfenkova/exercise/hw5/hw5-part-1-4.ipynb
  users/rmarfenkova/exercise/hw5/hw5-part-5.ipynb
Labels: 9 группа

#551 Update hw_status_0303
  library/streams/2024/hw_status
Labels: 6 группа

#552 Update visits_status_0303
  library/streams/2024/visits_status
Labels: 6 группа

#533 avlotsmanov-HW6 Алгоритм решения задач
  users/avlotsmanov/exercise/hw6/Instruction_GIT_Lotsmanov.ipynb
  users/avlotsmanov/exercise/hw6/hw6-avlotsmanov.ipynb
  users/avlotsmanov/exercise/hw6/hw6.pdf
Labels: 8 группа

#558 Update hw_status
  library/streams/2024/hw_status
Labels: 9 группа

#559 Update visits_status
  library/streams/2024/visits_status
Labels: 9 группа

#522 ДЗ 5
  users/eanabatov/exercise/hw-5/hw-5.ipynb
Labels: 3 группа

#553 Aemareev hw7 python
  users/aemareev/exercise/hw7/hw-7-part-1.ipynb
  users/aemareev/exercise/hw7/hw-7-part-2.ipynb
  users/aemareev/exercise/hw7/hw-7-part-check-yourself.ipynb
Labels: 3 группа

#561 роботы это что то
  users/rmarfenkova/exercise/hw6/hw6.ipynb
Labels: 9 группа

#557 HW-7
  users/oekorchevaya/exercise/hw-7/hw-7-part-1.ipynb
  users/oekorchevaya/exercise/hw-7/hw-7-part-2.ipynb
  users/oekorchevaya/exercise/hw-7/hw-7-part-check-yourself.ipynb
Labels: 8 группа

#562 avlotsmanov - HW7 - функции и циклы
  users/avlotsmanov/exercise/hw7/hw-7-part-1.ipynb
  users/avlotsmanov/exercise/hw7/hw-7-part-2.ipynb
  users/avlotsmanov/exercise/hw7/hw-7-part-check-yourself.ipynb
Labels: 8 группа

#521 Home work 5 part 5
  users/aaarisova/exercise/hw-5/hw-5-part-5.ipynb
Labels: 9 группа

#490 MVAndreeva hw5 part5
  users/mvandreeva/study2024/exercise/hw5/hw-5.ipynb
Labels: 1 группа

#574 Сделал hw-5-5
  users/rstarasov/exercise/hw-5/hw-5-5.ipynb
Labels: 1 группа

#581 rstarasov дополнил данные о выполнении ДЗ и посещаемости
  library/streams/2024/hw_status
  library/streams/2024/visits_status
Labels: 1 группа

#573 rmarfenkova_hw7
  users/rmarfenkova/exercise/hw7/hw-7-part-1.ipynb
  users/rmarfenkova/exercise/hw7/hw-7-part-2.ipynb
  users/rmarfenkova/exercise/hw7/hw-7-part-check-yourself.ipynb
Labels: 9 группа

#577 Bykov HW6
  users/vvbykov/exercise/hw6/hw-6.ipynb
Labels: 3 группа

#549 saivanov добавил неинтерактивную версию программы, рисующую траекторию робота из 2 задания hw6
  library/exercises/hw-6/robo2_pyplot_version.ipynb
Labels: 9 группа

#586 Added hw-8
  users/oekorchevaya/exercise/hw-8/hw8.ipynb
Labels: 8 группа

#591 Добавлено домашнее задание 6
  users/aaarisova/exercise/hw-6/hw-6.ipynb
Labels: 9 группа

#532 hw-6
  users/oekorchevaya/exercise/hw-6/hw_6.txt
Labels: 8 группа

#492 Irsalieva hw5 part1
  users/irsalieva/exercise/hw5/hw-5-part1.ipynb
  users/irsalieva/exercise/hw5/hw-5-part2.ipynb
  users/irsalieva/exercise/hw5/hw-5-part3.ipynb
  users/irsalieva/exercise/hw5/hw-5-part4.ipynb
Labels: 8 группа

#603 Update visits_status
  library/streams/2024/visits_status
Labels: 9 группа

#602 Update hw_status
  library/streams/2024/hw_status
Labels: 9 группа

#592 avlotsmanov - HW8 - Пишем тесты к функциии triangle_type
  users/avlotsmanov/exercise/hw8/hw8_lotsmanov.ipynb
Labels: 8 группа

#601 arisova-Hw-7-part-1
  users/aaarisova/exercise/hw-7/hw-7-part-1.ipynb
  users/aaarisova/exercise/hw-7/hw-7-part-2.ipynb
  users/aaarisova/exercise/hw-7/hw-7-part-check-yourself.ipynb
Labels: 9 группа

#604 Update visits_status
  library/streams/2024/visits_status
Labels: 2 группа

#605 Update hw_status
  library/streams/2024/hw_status
Labels: 2 группа

#575 Выполнила дз 7
  library/streams/2024/hw_status
  library/streams/2024/visits_status
  users/ismatrosova/exercise/hw7/hw-7-part-1.ipynb
  users/ismatrosova/exercise/hw7/hw-7-part-2.ipynb
  users/ismatrosova/exercise/hw7/hw-7-part-check-yourself.ipynb
Labels: 7 группа

#599 Aemareev-hw8-tests
  users/aemareev/exercise/hw8/hw8.ipynb
Labels: 3 группа

#621 VVBykov-Schedule
  users/vvbykov/hw_schedule_fact
  users/vvbykov/hw_schedule_plan
Labels: 3 группа

#619 VVBykov HW-7
  users/vvbykov/exercise/hw7/hw-7-part-1.ipynb
  users/vvbykov/exercise/hw7/hw-7-part-2.ipynb
  users/vvbykov/exercise/hw7/hw-7-part-check-yourself.ipynb
Labels: 3 группа

#624 Update visits_status_Arisova
  library/streams/2024/visits_status
Labels: 9 группа

#623 Update hw_status_Arisova
  library/streams/2024/hw_status
Labels: 9 группа

#620 Arisova-hw-8
  users/aaarisova/exercise/hw-8/hw8.ipynb
Labels: 9 группа

#626 HW8_rmarfenkova
  users/rmarfenkova/exercise/hw8/hw8.ipynb
  users/rmarfenkova/exercise/hw8/hw8_task.ipynb
Labels: 9 группа

#625 Arisova_hw-9_план-факт выаполнения моих д/з
  users/aaarisova/hw_schedule_fact
  users/aaarisova/hw_schedule_plan
Labels: 9 группа

#631 hw_status
  library/streams/2024/hw_status
Labels: 9 группа

#640 kaanikin обновил статус
  library/streams/2024/hw_status
  library/streams/2024/visits_status
Labels: 9 группа

#643 Update hw_status
  library/streams/2024/hw_status
Labels: 8 группа

#641 JATashpulatov - Add schedule plan and fact
  users/jatashpulatov/hw_schedule_fact
  users/jatashpulatov/hw_schedule_plan
Labels: 3 группа

#596 hw5_part5
  users/agvolodina/exercise/hw5/hw5_part5.ipynb
Labels: 1 группа

#598 Сделал hw6
  users/aavolodin/exercise/hw6/hw6.ipynb
Labels: 1 группа

#635 Create hw_schedule_plan
  users/aemareev/hw_schedule_fact
  users/aemareev/hw_schedule_plan
Labels: 3 группа

#648 rstarasov расписание личных занятий
  users/rstarasov/schedule/hw_schedule_plan
Labels: 1 группа

#644 hw_schedule_plan_rmarfenkova
  users/rmarfenkova/hw_schedule_plan.txt
Labels: 9 группа

#617 Ismatrosova hw 8
  library/streams/2024/hw_status
  library/streams/2024/visits_status
  users/ismatrosova/exercise/hw8/hw8.ipynb
Labels: 7 группа

#653 MVAndreeva hw status and shedule
  library/streams/2024/hw_status
  library/streams/2024/visits_status
  users/mvandreeva/study2024/hw_schedule_fact.txt
  users/mvandreeva/study2024/hw_schedule_plan.txt
Labels: 1 группа

#582 Сделал 5-ю часть HW5
  users/aavolodin/exercise/hw5/hw5_part5.ipynb
Labels: 1 группа

#659 aemareev update visits_status & hw_status
  library/streams/2024/hw_status
  library/streams/2024/visits_status
Labels: 3 группа

#483 Aomargolina hw3
  users/aomargolina/exercice/hw3/HW3 part 2.ipynb
  users/aomargolina/exercice/hw3/hw-3-part-1
Labels: 6 группа

#665 Update hw_status
  library/streams/2024/hw_status
Labels: 6 группа

#658 aemareev-hw9-tests
  users/aemareev/exercise/hw9/functions_hw5.py
  users/aemareev/exercise/hw9/functions_hw7.py
  users/aemareev/exercise/hw9/test_functions_hw5.py
  users/aemareev/exercise/hw9/test_functions_hw7.py
Labels: 3 группа

#646 Avmorozova 7hw
  users/avmorozova/exercise/hw5/hw5_3.ipynb
  users/avmorozova/exercise/hw5/hw5_all.ipynb
  users/avmorozova/exercise/hw7/hw-7-part-check-yourself.ipynb
  users/avmorozova/exercise/hw7/hw7-1.ipynb
  users/avmorozova/exercise/hw7/hw7-2.ipynb
Labels: 3 группа

#667 Update hw_schedule_fact
  users/aemareev/hw_schedule_fact
Labels: 3 группа

#661 Agvolodina hw7
  users/agvolodina/exercise/hw7/hw-7-part-1.ipynb
  users/agvolodina/exercise/hw7/hw-7-part-2.ipynb
  users/agvolodina/exercise/hw7/hw-7-part-check-yourself.ipynb
Labels: 1 группа

#647 Mvandreeva hw7
  users/mvandreeva/study2024/exercise/hw7/hw-7-part-1.ipynb
  users/mvandreeva/study2024/exercise/hw7/hw-7-part-2.ipynb
  users/mvandreeva/study2024/exercise/hw7/hw-7-part-check-yourself.ipynb
Labels: 1 группа

#634 MVAndreeva hw6
  users/mvandreeva/study2024/exercise/hw6/hw6.ipynb
  users/mvandreeva/study2024/exercise/hw6/hw6.pdf
Labels: 1 группа

#618 rstarasov hw7-part1
  users/rstarasov/exercise/hw-7/hw-7-part-1.ipynb
  users/rstarasov/exercise/hw-7/hw-7-part-2.ipynb
  users/rstarasov/exercise/hw-7/hw-7-part-check-yourself.ipynb
Labels: 1 группа

#630 Cделал hw7-part1
  users/aavolodin/exercise/hw7/hw-7-part-1.ipynb
  users/aavolodin/exercise/hw7/hw-7-part-2.ipynb
  users/aavolodin/exercise/hw7/hw-7-part-check-yourself.ipynb
  users/aavolodin/hw_schedule_fact.txt
  users/aavolodin/hw_schedule_plan.txt
Labels: 1 группа

#662 Arisova_HW-9_Тесты к hw-3
  users/aaarisova/exercise/hw-3/test-3/functions_hw_3.py
  users/aaarisova/exercise/hw-3/test-3/test_hw_3.py
Labels: 9 группа

#651 Ismatrosova hw 9
  library/streams/2024/hw_status
  users/ismatrosova/exercise/hw5/hw_5.py
  users/ismatrosova/exercise/hw5/test_hw_5.py
Labels: 7 группа

#666 rstarasov hw-7-part-2
  users/rstarasov/exercise/hw-7/hw-7-part-2-new.ipynb
  users/rstarasov/exercise/hw-7/hw-7-part-check-yourself-new.ipynb
Labels: 1 группа

#660 kaanikin тесты для HW3
  users/kaanikin/exercise/hw3/hw3.py
  users/kaanikin/exercise/hw3/test_hw3.py
Labels: 9 группа

#673 Arisova_Update visits_status
  library/streams/2024/visits_status
Labels: 9 группа

#672 Arisova_Update hw_status
  library/streams/2024/hw_status
Labels: 9 группа

#668 VVBykov HW8 completed
  users/vvbykov/exercise/hw8/hw8.ipynb
Labels: 3 группа

#671 agvolodina_hw8
  users/agvolodina/exercise/hw8/hw8.ipynb
  users/agvolodina/exercise/hw8/hw8_1.ipynb
Labels: 1 группа

#686 Сделал ДЗ№8
  users/aavolodin/exercise/hw8/hw8.ipynb
Labels: 1 группа

#695 kaanikin добавил номер группы
  library/streams/2024/groups
Labels: 9 группа

#692 Update 8 group
  library/streams/2024/groups
Labels: 8 группа

#694 Arisova_Update groups
  library/streams/2024/groups
Labels: 9 группа

#697 Ismatrosova Update groups
  library/streams/2024/groups
Labels: 7 группа

#700 MVAndreeva update group and hw/visit status
  library/streams/2024/groups
  library/streams/2024/hw_status
  library/streams/2024/visits_status
Labels: 1 группа

#702 rstarasov добавил инфо о готовности ДЗ, посещаемости и указал свою группу
  library/streams/2024/groups
  library/streams/2024/hw_status
  library/streams/2024/visits_status
Labels: 1 группа
