Repository amtsu/team22, pull requests merged in 2024-04, with the labels that each got.

#652 tarasovavs HW-8
  users/vstarasova/exercise/hw8/HW-8.ipynb
Labels: 2 группа

#607 HW 7 vstarasova (3 parts)
  users/vstarasova/exercise/hw7/hw-7-part-1.ipynb
  users/vstarasova/exercise/hw7/hw-7-part-2.ipynb
  users/vstarasova/exercise/hw7/hw-7-part-check-yourself.ipynb
Labels: 2 группа

#712 Update visits_status
  library/streams/2024/visits_status
Labels: 8 группа

#711 Update hw_status
  library/streams/2024/hw_status
Labels: 8 группа

#688 rstarasov schedules
  users/rstarasov/schedule/hw_schedule_fact
  users/rstarasov/schedule/hw_schedule_plan
Labels: 1 группа

#679 Update visits_status
  library/streams/2024/visits_status
Labels: 1 группа

#678 Update hw_status
  library/streams/2024/hw_status
Labels: 1 группа

#689 MVAndreeva hw8
  users/mvandreeva/study2024/exercise/hw8_test_triangle/hw8.ipynb
Labels: 1 группа

#713 Update visits_status
  library/streams/2024/visits_status
Labels: 1 группа

#714 Update hw_status
  library/streams/2024/hw_status
Labels: 1 группа

#683 Avmorozova 8hw
  users/avmorozova/exercise/hw7/hw7-2.ipynb
  users/avmorozova/exercise/hw7/hw_7.ipynb
  users/avmorozova/exercise/hw8/hw8-1.ipynb
Labels: 3 группа

#710 JATashpulatov - hw7 (all parts)
  users/jatashpulatov/exercise/hw-7/hw-7-part-1.ipynb
  users/jatashpulatov/exercise/hw-7/hw-7-part-2.ipynb
  users/jatashpulatov/exercise/hw-7/hw-7-part-check-yourself.ipynb
Labels: 3 группа

#529 hw5-part4
  users/aomargolina/exercice/hw5/hw-5-part4.ipynb
Labels: 6 группа

#527 HW5 part 1-3
  users/aomargolina/exercice/hw5/hw-5/hw-5-part-1_3.ipynb
Labels: 6 группа

#482 Aomargolina hw4
  users/aomargolina/exercice/hw4/hw4.ipynb
Labels: 6 группа

#704 Update groups
  library/streams/2024/groups
Labels: 2 группа

#716 JATashpulatov - Update hw_status & visits_status
  library/streams/2024/hw_status
  library/streams/2024/visits_status
Labels: 3 группа

#687 rstarasov выполнил hw-8
  users/rstarasov/exercise/hw-8/hw8.ipynb
Labels: 1 группа

#674 kaanikin hw9 добавил часть с hw4
  users/kaanikin/exercise/hw4/hw4.py
  users/kaanikin/exercise/hw4/test_hw4.py
Labels: 9 группа

#707 Rgyusupov hw 6
  library/streams/2024/hw_status
  library/streams/2024/visits_status
  users/rgyusupov/exercise/hw6/hw-6.ipynb
Labels: 6 группа

#709 hw8 - testing functions
  users/rgyusupov/exercise/hw8/triangle_type_func_broken.py
  users/rgyusupov/exercise/hw8/triangle_type_func_from_task.py
  users/rgyusupov/exercise/hw8/triangle_type_func_updated_raise_error.py
Labels: 6 группа

#717 Ismatrosova working time
  library/working_time/ismatrosova_working_time.py
  library/working_time/test_ismatrosova_working_time.py
  users/ismatrosova/exercise/working_time/test_working_time.py
  users/ismatrosova/exercise/working_time/working_time.ipynb
  users/ismatrosova/exercise/working_time/working_time.py
Labels: 7 группа

#670 Arisova_HW-9 тесты к hw-4
  users/aaarisova/exercise/hw-4/test-4/functions_hw_4.py
  users/aaarisova/exercise/hw-4/test-4/test_hw_4.py
Labels: 9 группа

#708 kaanikin_hw9 первые две части hw5
  users/kaanikin/exercise/hw5/hw5_part1.py
  users/kaanikin/exercise/hw5/hw5_part2.py
  users/kaanikin/exercise/hw5/test_hw5_part1.py
  users/kaanikin/exercise/hw5/test_hw5_part2.py
Labels: 9 группа

#723 homework7
  users/rnyunusov/exercise/hw7/hw-7-part-1.ipynb
  users/rnyunusov/exercise/hw7/hw-7-part-2.ipynb
  users/rnyunusov/exercise/hw7/hw-7-part-check-yourself.ipynb
Labels: 1 группа

#650 HW9_RMARFENKOVA готово
  users/rmarfenkova/exercise/hw9/for_hw3/func_for_hw3.py
  users/rmarfenkova/exercise/hw9/for_hw3/test_func_for_hw3.py
  users/rmarfenkova/exercise/hw9/for_hw4/func_for_hw4.py
  users/rmarfenkova/exercise/hw9/for_hw4/test_func_for_hw4.py
  users/rmarfenkova/exercise/hw9/for_hw5/func_for_hw5.py
  users/rmarfenkova/exercise/hw9/for_hw5/func_for_hw5_1_4.py
  users/rmarfenkova/exercise/hw9/for_hw5/test_func_for_hw5.py
  users/rmarfenkova/exercise/hw9/for_hw5/test_func_for_hw5_1_4.py
  users/rmarfenkova/exercise/hw9/for_hw7/func_for_hw7.py
  users/rmarfenkova/exercise/hw9/for_hw7/test_func_for_hw7.py
  users/rmarfenkova/exercise/hw9/output.txt
Labels: 9 группа

#656 Arisova_HW-9 -тесты к hw-5-к частям 1-4
  users/aaarisova/exercise/hw-5/test-5/functions_hw_5.py
  users/aaarisova/exercise/hw-5/test-5/functions_hw_5_p5.py
  users/aaarisova/exercise/hw-5/test-5/test_hw_5.py
  users/aaarisova/exercise/hw-5/test-5/test_hw_5_p5.py
Labels: 9 группа

#722 vvbykov-HW9
  users/vvbykov/exercise/hw9/hw9_functions.py
  users/vvbykov/exercise/hw9/test_hw9_functions.py
  users/vvbykov/exercise/hw9/test_results
Labels: 3 группа

#740 VVBykov status update
  library/streams/2024/hw_status
  library/streams/2024/visits_status
Labels: 3 группа

#732 aemareev-hw11-python
  users/aemareev/exercise/hw11/example.txt
  users/aemareev/exercise/hw11/file1.txt
  users/aemareev/exercise/hw11/file2n.txt
  users/aemareev/exercise/hw11/file2n1.txt
  users/aemareev/exercise/hw11/hw-11.ipynb
  users/aemareev/hw_schedule_fact
  users/aemareev/hw_schedule_plan
Labels: 3 группа

#742 Update hw_status
  library/streams/2024/hw_status
Labels: 2 группа

#637 tarasovavs Файл с расписанием проработок
  users/vstarasova/hw_schedule_plan_vstarasova.txt
Labels: 2 группа

#744 Vstarasova hw9
  users/vstarasova/exercise/hw9/hw9_functions.py
  users/vstarasova/exercise/hw9/hw9_tests.py
Labels: 2 группа

#736 Agvolodina hw9
  users/agvolodina/exercise/hw9/func_dict.py
  users/agvolodina/exercise/hw9/func_if_and_for.py
  users/agvolodina/exercise/hw9/func_set.py
  users/agvolodina/exercise/hw9/test_func_dict.py
  users/agvolodina/exercise/hw9/test_func_if_and_for.py
  users/agvolodina/exercise/hw9/test_func_set.py
Labels: 1 группа

#745 rnyunusov-hw8
  users/rnyunusov/exercise/hw8/hw8.ipynb
Labels: 1 группа

#746 MVAndreeva status and shedule
  library/streams/2024/hw_status
  library/streams/2024/visits_status
  users/mvandreeva/study2024/hw_schedule_fact.txt
  users/mvandreeva/study2024/hw_schedule_plan.txt
Labels: 1 группа

#747 Update visits_status
  library/streams/2024/visits_status
Labels: 1 группа

#748 Update hw_status
  library/streams/2024/hw_status
Labels: 1 группа

#749 Update hw_schedule_plan.txt
  users/agvolodina/hw_schedule_plan.txt
Labels: 1 группа

#750 Update hw_schedule_plan
  users/aaarisova/hw_schedule_plan
Labels: 9 группа

#669 hw-9 ismatrosova добавила больше тестов
  users/ismatrosova/exercise/hw5/hw_5.py
  users/ismatrosova/exercise/hw5/test_hw_5.py
Labels: 7 группа

#446 сделал дз№3 (часть2)
  users/SAMaltsev/SAMaltsev2024/exercise/hw-3/hw-3-2.ipynb
Labels: 4 группа

#764 kaanikin обновил статусы
  library/streams/2024/hw_status
  library/streams/2024/visits_status
Labels: 9 группа

#728 Arisova HW-12_parts_1_and_2
  users/aaarisova/exercise/hw-12/bank_account.py
  users/aaarisova/exercise/hw-12/book.py
  users/aaarisova/exercise/hw-12/car.py
  users/aaarisova/exercise/hw-12/circle.py
  users/aaarisova/exercise/hw-12/date.py
  users/aaarisova/exercise/hw-12/p_2_polygon.py
  users/aaarisova/exercise/hw-12/p_2_shape.py
  users/aaarisova/exercise/hw-12/p_2_student_registry.py
  users/aaarisova/exercise/hw-12/point.py
  users/aaarisova/exercise/hw-12/shopping_cart.py
  users/aaarisova/exercise/hw-12/student.py
  users/aaarisova/exercise/hw-12/test_bank_account.py
  users/aaarisova/exercise/hw-12/test_book.py
  users/aaarisova/exercise/hw-12/test_car.py
  users/aaarisova/exercise/hw-12/test_circle.py
  users/aaarisova/exercise/hw-12/test_date.py
  users/aaarisova/exercise/hw-12/test_p_2_polygon.py
  users/aaarisova/exercise/hw-12/test_p_2_shape.py
  users/aaarisova/exercise/hw-12/test_p_2_student_registry.py
  users/aaarisova/exercise/hw-12/test_point.py
  users/aaarisova/exercise/hw-12/test_shopping_cart.py
  users/aaarisova/exercise/hw-12/test_student.py
  users/aaarisova/exercise/hw-12/test_triangle.py
  users/aaarisova/exercise/hw-12/triangle.py
Labels: 9 группа

#731 HW_12_RMARFENKOVA
  users/rmarfenkova/exercise/hw12/Shape.py
  users/rmarfenkova/exercise/hw12/bank_account.py
  users/rmarfenkova/exercise/hw12/class_Book.py
  users/rmarfenkova/exercise/hw12/class_Car.py
  users/rmarfenkova/exercise/hw12/class_Circle.py
  users/rmarfenkova/exercise/hw12/class_Date.py
  users/rmarfenkova/exercise/hw12/class_Point.py
  users/rmarfenkova/exercise/hw12/class_Polygon.py
  users/rmarfenkova/exercise/hw12/class_ShoppingCart.py
  users/rmarfenkova/exercise/hw12/class_Student.py
  users/rmarfenkova/exercise/hw12/class_Triangle.py
  users/rmarfenkova/exercise/hw12/class_University.py
  users/rmarfenkova/exercise/hw12/hw-12-part-1.ipynb
  users/rmarfenkova/exercise/hw12/test_Circle.py
  users/rmarfenkova/exercise/hw12/test_Date.py
  users/rmarfenkova/exercise/hw12/test_Shape.py
  users/rmarfenkova/exercise/hw12/test_Triangle.py
  users/rmarfenkova/exercise/hw12/test_University.py
  users/rmarfenkova/exercise/hw12/test_bank_account.py
  users/rmarfenkova/exercise/hw12/test_class_Book.py
  users/rmarfenkova/exercise/hw12/test_class_Car.py
  users/rmarfenkova/exercise/hw12/test_class_Polygon.py
  users/rmarfenkova/exercise/hw12/test_class_ShoppingCart.py
  users/rmarfenkova/exercise/hw12/test_class_Student.py
  users/rmarfenkova/exercise/hw12/tests_Point.py
Labels: 9 группа

#720 Mvandreeva hw9
  users/mvandreeva/study2024/exercise/hw9_tests/some_func_hw5.py
  users/mvandreeva/study2024/exercise/hw9_tests/test_some_func_hw5.py
Labels: 1 группа

#772 aemareev-updated-statuses-and-plans
  library/streams/2024/hw_status
  library/streams/2024/hw_status.csv
  library/streams/2024/visits_status
  library/streams/2024/visits_status.csv
  users/aemareev/hw_schedule_fact
  users/aemareev/hw_schedule_plan
Labels: 3 группа

#770 aemareev-hw12-oop
  users/aemareev/exercise/hw12/bank_account.py
  users/aemareev/exercise/hw12/book.py
  users/aemareev/exercise/hw12/car.py
  users/aemareev/exercise/hw12/circle.py
  users/aemareev/exercise/hw12/date.py
  users/aemareev/exercise/hw12/education_institution.py
  users/aemareev/exercise/hw12/matrix.py
  users/aemareev/exercise/hw12/point.py
  users/aemareev/exercise/hw12/polygon.py
  users/aemareev/exercise/hw12/shape.py
  users/aemareev/exercise/hw12/shopping_cart.py
  users/aemareev/exercise/hw12/student.py
  users/aemareev/exercise/hw12/triangle.py
  users/aemareev/exercise/hw12/warehouse.py
Labels: 3 группа

#547 Avnepo hw7
  users/anton-kuvalda/exercise/hw4/avnepo_hw4_1-3.ipynb
  users/anton-kuvalda/exercise/hw4/avnepo_hw4_1_3.ipynb
  users/anton-kuvalda/exercise/hw5/avnepo_hw5.ipynb
  users/anton-kuvalda/exercise/hw5/avnepo_hw5_p2.ipynb
  users/anton-kuvalda/exercise/hw7/hw7.ipynb
  users/avnepo/README.md
  users/avnepo/exercise/hw1/result_history
Labels: 2 группа

#776 Avmorozova 9hw все тоже ,но новую ветку правильно создала и без ненужных файлов
  users/avmorozova/exercise/hw9/func (1).py
  users/avmorozova/exercise/hw9/test_func.py
Labels: 3 группа

#778 aemareev_hw13_parts_1-2
  users/aemareev/exercise/hw13/car.py
  users/aemareev/exercise/hw13/default.pickle
  users/aemareev/exercise/hw13/education_institution.py
  users/aemareev/exercise/hw13/file_methods.py
  users/aemareev/exercise/hw13/matrix.py
  users/aemareev/exercise/hw13/order.pickle
  users/aemareev/exercise/hw13/shape.py
  users/aemareev/exercise/hw13/shape_circle.pickle
  users/aemareev/exercise/hw13/shape_rectangle.pickle
  users/aemareev/exercise/hw13/shape_triangle.pickle
  users/aemareev/exercise/hw13/shopping_cart.py
  users/aemareev/exercise/hw13/student.py
  users/aemareev/exercise/hw13/warehouse.pickle
  users/aemareev/exercise/hw13/warehouse.py
Labels: 3 группа

#783 Update hw_status.csv
  library/streams/2024/hw_status.csv
Labels: 2 группа

#786 Update hw_status.csv
  library/streams/2024/hw_status.csv
Labels: 2 группа

#781 Сделал hw9
  users/aavolodin/exercise/hw9/func_dict.py
  users/aavolodin/exercise/hw9/func_set.py
  users/aavolodin/exercise/hw9/test_func_dict.py
  users/aavolodin/exercise/hw9/test_func_set.py
Labels: 1 группа

#769 rstarasov hw-9
  users/rstarasov/exercise/hw-9/tests_for_hw5/hw5_defs.py
  users/rstarasov/exercise/hw-9/tests_for_hw5/test_hw5_defs.py
Labels: 1 группа
