Repository amtsu/team22, pull requests merged in 2024-07, with the labels that each got.

#880 Aemareev status updates
  library/streams/2024/hw_status.csv
  library/streams/2024/visits_status.csv
Labels: 3 группа

#874 kaanikin- team.html
  library/streams/2024/team.html
Labels: 9 группа

#881 Aomargolina cv
  library/streams/2024/team.html
Labels: 2 группа

#884 Update team.html
  library/streams/2024/team.html
Labels: 2 группа

#890 Arisova_Update visits_status.csv
  library/streams/2024/visits_status.csv
Labels: 9 группа

#889 Arisova_Update hw_status.csv
  library/streams/2024/hw_status.csv
Labels: 9 группа
