Repository amtsu/team22, pull requests merged in 2024-06, with the labels that each got.

#843 Update groups.csv
  library/streams/2024/groups.csv
Labels: 2 группа

#844 Update groups.csv
  library/streams/2024/groups.csv
Labels: 3 группа

#845 Update hw-1.csv
  library/exercises/hw-html/hw-1.csv
Labels: 1 группа

#851 Update hw_status.csv
  library/streams/2024/hw_status.csv
Labels: 1 группа

#852 Update visits_status.csv
  library/streams/2024/visits_status.csv
Labels: 1 группа

#850 Update visits_status.csv
  library/streams/2024/visits_status.csv
Labels: 9 группа

#853 Update 11/06 hw_status.csv
  library/streams/2024/hw_status.csv
Labels: 2 группа

#841 часть 11 задания
  users/aomargolina/exercice/hw11/hw11.ipynb
Labels: 2 группа

#855 aemareev Update team.html
  library/streams/2024/team.html
Labels: 3 группа

#839 rnyunusov hw11
  users/rnyunusov/exercise/hw11/file1.txt
  users/rnyunusov/exercise/hw11/file2.txt
  users/rnyunusov/exercise/hw11/file2n.txt
  users/rnyunusov/exercise/hw11/file2n1.txt
  users/rnyunusov/exercise/hw11/hw-11.ipynb
Labels: 1 группа

#859 добавил ссылку в кавычках в team.html
  library/streams/2024/team.html
Labels: 2 группа

#860 изменение в файле команды - добавление ссылки
  library/streams/2024/team.html
Labels: 2 группа

#861 Mvandreeva resume
  library/streams/2024/team.html
  users/mvandreeva/study2024/exercise/resume/image004-49.jpg
  users/mvandreeva/study2024/exercise/resume/index.html
  users/mvandreeva/study2024/exercise/resume/style.css
Labels: 1 группа

#863 Update team.html
  library/streams/2024/team.html
Labels: 2 группа

#842 Aomargolina hw7
  users/aomargolina/exercice/hw7/hw-7-part-check-yourself.ipynb
Labels: 2 группа

#820 hw12 часть 1, пока без тестов
  users/aavolodin/exercise/hw12/hw-12-part-1.ipynb
Labels: 1 группа

#848 Update hw_status.csv
  library/streams/2024/hw_status.csv
Labels: 2 группа

#872 Update hw_status.csv
  library/streams/2024/hw_status.csv
Labels: 2 группа

#873 Update visits_status.csv
  library/streams/2024/visits_status.csv
Labels: 2 группа

#854 Резюме (без информативного содержания, за 3 минуты)
  users/vstarasova/exercise/html/about.html
  users/vstarasova/exercise/html/photo_2024.jpg
Labels: 2 группа

#877 team.html
  library/streams/2024/team.html
Labels: 2 группа

#876 Update team.html
  library/streams/2024/team.html
Labels: 2 группа
