Repository amtsu/team22, pull requests merged in 2024-05, with the labels that each got.

#793 aemareev-update-status
  library/streams/2024/hw_status.csv
  library/streams/2024/visits_status.csv
Labels: 3 группа

#788 Kaanikin hw12
  users/kaanikin/exercise/hw-12/part3_Matrix.py
  users/kaanikin/exercise/hw-12/test_part3_Matrix.py
Labels: 9 группа

#777 HW_11_RMARFENKOVA
  users/rmarfenkova/exercise/hw11/file1.txt
  users/rmarfenkova/exercise/hw11/file2n.txt
  users/rmarfenkova/exercise/hw11/file2n1.txt
  users/rmarfenkova/exercise/hw11/hw-11.ipynb
Labels: 9 группа

#792 aemareev-hw13-part3
  users/aemareev/exercise/hw13/part_3/handlers.py
  users/aemareev/exercise/hw13/part_3/main.py
  users/aemareev/exercise/hw13/part_3/test_hw_status.csv
  users/aemareev/exercise/hw13/part_3/test_visits_status.csv
Labels: 3 группа

#780 Arisova HW-11
  users/aaarisova/exercise/hw-11/file1.txt
  users/aaarisova/exercise/hw-11/file1n.txt
  users/aaarisova/exercise/hw-11/file2.txt
  users/aaarisova/exercise/hw-11/file2n.txt
  users/aaarisova/exercise/hw-11/file_merge.txt
  users/aaarisova/exercise/hw-11/hw-11.ipynb
Labels: 9 группа

#782 kaanikin hw-11 выполнено
  users/kaanikin/exercise/hw-11/file1.txt
  users/kaanikin/exercise/hw-11/file2n.txt
  users/kaanikin/exercise/hw-11/file2n1.txt
  users/kaanikin/exercise/hw-11/hw-11.ipynb
Labels: 9 группа

#796 aemareev-hw15-csv-updater
  library/streams/2024/hw_status.csv
  library/streams/2024/visits_status.csv
  users/aemareev/exercise/hw15/status_update.py
Labels: 3 группа

#790 RMARFENKOVA_HW_12_PART_3
  users/rmarfenkova/exercise/hw12/class_Matrix.py
  users/rmarfenkova/exercise/hw12/class_Warehouse.py
  users/rmarfenkova/exercise/hw12/hw-12-part-1.ipynb
  users/rmarfenkova/exercise/hw12/hw-12-part-2.ipynb
  users/rmarfenkova/exercise/hw12/hw-12-part-3.ipynb
  users/rmarfenkova/exercise/hw12/test_class_Matrix.py
  users/rmarfenkova/exercise/hw12/test_lass_Warehouse.py
Labels: 9 группа

#791 Arisova_HW-12-p3 Warehouse + Matrix
  users/aaarisova/exercise/hw-12/matrix.py
  users/aaarisova/exercise/hw-12/test_matrix.py
  users/aaarisova/exercise/hw-12/test_warehouse.py
  users/aaarisova/exercise/hw-12/warehouse.py
Labels: 9 группа

#813 Update visits_status.csv
  library/streams/2024/visits_status.csv
Labels: 9 группа

#812 Update hw_status.csv
  library/streams/2024/hw_status.csv
Labels: 9 группа

#815 aemareev hw & visit statuses update
  library/streams/2024/hw_status.csv
  library/streams/2024/visits_status.csv
Labels: 3 группа

#811 Vstarasova hw12 new12
  users/vstarasova/exercise/hw12/All_classes.py
  users/vstarasova/exercise/hw12/BankAccount.py
  users/vstarasova/exercise/hw12/Book.py
  users/vstarasova/exercise/hw12/Car.py
  users/vstarasova/exercise/hw12/Car2.py
  users/vstarasova/exercise/hw12/Chto-to.py
  users/vstarasova/exercise/hw12/Circle.py
  users/vstarasova/exercise/hw12/Circle2.py
  users/vstarasova/exercise/hw12/Date.py
  users/vstarasova/exercise/hw12/MAI.py
  users/vstarasova/exercise/hw12/Point.py
  users/vstarasova/exercise/hw12/Polygon.py
  users/vstarasova/exercise/hw12/Shape.py
  users/vstarasova/exercise/hw12/ShoppingCart.py
  users/vstarasova/exercise/hw12/Student.py
  users/vstarasova/exercise/hw12/Student2.py
  users/vstarasova/exercise/hw12/Triangle.py
  users/vstarasova/exercise/hw12/Triangle2.py
  users/vstarasova/exercise/hw12/test_BankAccount.py
  users/vstarasova/exercise/hw12/test_Book.py
  users/vstarasova/exercise/hw12/test_Car.py
  users/vstarasova/exercise/hw12/test_Car2.py
  users/vstarasova/exercise/hw12/test_Circle.py
  users/vstarasova/exercise/hw12/test_Date.py
  users/vstarasova/exercise/hw12/test_MAI.py
  users/vstarasova/exercise/hw12/test_Point.py
  users/vstarasova/exercise/hw12/test_Polygon.py
  users/vstarasova/exercise/hw12/test_Shape.py
  users/vstarasova/exercise/hw12/test_ShoppingCart.py
  users/vstarasova/exercise/hw12/test_Student.py
  users/vstarasova/exercise/hw12/test_Student2.py
  users/vstarasova/exercise/hw12/test_Triangle.py
Labels: 2 группа

#814 Aemareev hw14 algorithms
  users/aemareev/exercise/hw14/linux_tree.py
  users/aemareev/exercise/hw14/task-1-complexity.ipynb
  users/aemareev/exercise/hw14/task-2-list-sort.ipynb
  users/aemareev/exercise/hw14/task-3-tree.ipynb
Labels: 3 группа

#817 Update hw_status.csv
  library/streams/2024/hw_status.csv
Labels: 3 группа

#801 rstarasov hw-11
  users/rstarasov/exercise/hw-11/file2n.txt
  users/rstarasov/exercise/hw-11/file2n1.txt
  users/rstarasov/exercise/hw-11/first.txt
  users/rstarasov/exercise/hw-11/hw-11.ipynb
  users/rstarasov/exercise/hw-11/temp.txt
Labels: 1 группа

#789 Arisova_hw-13-p1,p2 готово
  users/aaarisova/exercise/hw_13/car_extended.py
  users/aaarisova/exercise/hw_13/circle.pkl
  users/aaarisova/exercise/hw_13/file_car.pickle
  users/aaarisova/exercise/hw_13/file_student.pickle
  users/aaarisova/exercise/hw_13/matrix.pkl
  users/aaarisova/exercise/hw_13/matrix_extended.py
  users/aaarisova/exercise/hw_13/rectangle.pkl
  users/aaarisova/exercise/hw_13/shape_circle.py
  users/aaarisova/exercise/hw_13/shape_extended.py
  users/aaarisova/exercise/hw_13/shape_rectangle.py
  users/aaarisova/exercise/hw_13/shape_triangle.py
  users/aaarisova/exercise/hw_13/stud_registr_extended.py
  users/aaarisova/exercise/hw_13/student_extended.py
  users/aaarisova/exercise/hw_13/students_registry.pkl
  users/aaarisova/exercise/hw_13/test_car.py
  users/aaarisova/exercise/hw_13/test_matrix.py
  users/aaarisova/exercise/hw_13/test_shape.py
  users/aaarisova/exercise/hw_13/test_student.py
  users/aaarisova/exercise/hw_13/test_student_registry.py
  users/aaarisova/exercise/hw_13/test_warehouse.py
  users/aaarisova/exercise/hw_13/triangle.pkl
  users/aaarisova/exercise/hw_13/warehouse.pkl
  users/aaarisova/exercise/hw_13/warehouse_extended.py
Labels: 9 группа

#800 Kaanikin hw12
  users/kaanikin/exercise/hw-12/part3_Warehouse.py
  users/kaanikin/exercise/hw-12/test_part3_Warehouse.py
Labels: 9 группа

#823 Kaanikin hw14
  users/kaanikin/exercise/hw-14/task-1-complexity.ipynb
  users/kaanikin/exercise/hw-14/task-2-list-sort.ipynb
Labels: 9 группа

#798 Mvandreeva hw12
  users/mvandreeva/study2024/exercise/hw12_classes/bank.py
  users/mvandreeva/study2024/exercise/hw12_classes/books.py
  users/mvandreeva/study2024/exercise/hw12_classes/cars.py
  users/mvandreeva/study2024/exercise/hw12_classes/cart.py
  users/mvandreeva/study2024/exercise/hw12_classes/circle.py
  users/mvandreeva/study2024/exercise/hw12_classes/dates.py
  users/mvandreeva/study2024/exercise/hw12_classes/hw-12-part-1.ipynb
  users/mvandreeva/study2024/exercise/hw12_classes/hw-12-part-2.ipynb
  users/mvandreeva/study2024/exercise/hw12_classes/hw-12-part-3.ipynb
  users/mvandreeva/study2024/exercise/hw12_classes/part3/matrix.py
  users/mvandreeva/study2024/exercise/hw12_classes/part3/test_matrix.py
  users/mvandreeva/study2024/exercise/hw12_classes/part3/test_wh.py
  users/mvandreeva/study2024/exercise/hw12_classes/part3/wh_order.py
  users/mvandreeva/study2024/exercise/hw12_classes/part3/wh_order_register.py
  users/mvandreeva/study2024/exercise/hw12_classes/part3/wh_product.py
  users/mvandreeva/study2024/exercise/hw12_classes/part3/wh_warehouse.py
  users/mvandreeva/study2024/exercise/hw12_classes/points.py
  users/mvandreeva/study2024/exercise/hw12_classes/polygon.py
  users/mvandreeva/study2024/exercise/hw12_classes/shape.py
  users/mvandreeva/study2024/exercise/hw12_classes/student.py
  users/mvandreeva/study2024/exercise/hw12_classes/student_list.py
  users/mvandreeva/study2024/exercise/hw12_classes/test_bank.py
  users/mvandreeva/study2024/exercise/hw12_classes/test_books.py
  users/mvandreeva/study2024/exercise/hw12_classes/test_cars.py
  users/mvandreeva/study2024/exercise/hw12_classes/test_cart.py
  users/mvandreeva/study2024/exercise/hw12_classes/test_circle.py
  users/mvandreeva/study2024/exercise/hw12_classes/test_dates.py
  users/mvandreeva/study2024/exercise/hw12_classes/test_polygon.py
  users/mvandreeva/study2024/exercise/hw12_classes/test_students.py
  users/mvandreeva/study2024/exercise/hw12_classes/test_students_list.py
  users/mvandreeva/study2024/exercise/hw12_classes/test_triangles.py
  users/mvandreeva/study2024/exercise/hw12_classes/triangles.py
Labels: 1 группа

#825 VVBykov-HW12
  users/vvbykov/exercise/hw12/bankaccount.py
  users/vvbykov/exercise/hw12/book.py
  users/vvbykov/exercise/hw12/car.py
  users/vvbykov/exercise/hw12/circle.py
  users/vvbykov/exercise/hw12/institution.py
  users/vvbykov/exercise/hw12/matrix.py
  users/vvbykov/exercise/hw12/mydate.py
  users/vvbykov/exercise/hw12/point.py
  users/vvbykov/exercise/hw12/polygone.py
  users/vvbykov/exercise/hw12/rectangle.py
  users/vvbykov/exercise/hw12/shape.py
  users/vvbykov/exercise/hw12/shop.py
  users/vvbykov/exercise/hw12/shoppingcart.py
  users/vvbykov/exercise/hw12/student.py
  users/vvbykov/exercise/hw12/test.ipynb
  users/vvbykov/exercise/hw12/tests/test_bankaccount.py
  users/vvbykov/exercise/hw12/tests/test_book.py
  users/vvbykov/exercise/hw12/tests/test_car.py
  users/vvbykov/exercise/hw12/tests/test_circle.py
  users/vvbykov/exercise/hw12/tests/test_institution.py
  users/vvbykov/exercise/hw12/tests/test_matrix.py
  users/vvbykov/exercise/hw12/tests/test_mydate.py
  users/vvbykov/exercise/hw12/tests/test_point.py
  users/vvbykov/exercise/hw12/tests/test_polygone.py
  users/vvbykov/exercise/hw12/tests/test_rectangle.py
  users/vvbykov/exercise/hw12/tests/test_results
  users/vvbykov/exercise/hw12/tests/test_shoppingcart.py
  users/vvbykov/exercise/hw12/tests/test_student.py
  users/vvbykov/exercise/hw12/tests/test_triangle.py
  users/vvbykov/exercise/hw12/triangle.py
Labels: 3 группа

#787 Find y hw7
  users/yaauster/exercise/hw7/hw-7-part-1.ipynb
  users/yaauster/exercise/hw7/hw-7-part-1.ipynb.invalid
  users/yaauster/exercise/hw7/hw-7-part-2.ipynb
  users/yaauster/exercise/hw7/hw-7-part-check-yourself.ipynb
Labels: 9 группа

#831 MVAndreeva hw-visit-status
  library/streams/2024/hw_status.csv
  library/streams/2024/visits_status.csv
Labels: 1 группа

#828 RMARFENKOVA_HW14_task1_task2
  users/rmarfenkova/exercise/hw14/task-1-complexity.ipynb
  users/rmarfenkova/exercise/hw14/task-2-list-sort.ipynb
Labels: 9 группа

#832 VVBykov-Status update
  library/streams/2024/hw_status.csv
  library/streams/2024/visits_status.csv
Labels: 3 группа

#834 rstarasov update visits_status.csv
  library/streams/2024/visits_status.csv
Labels: 1 группа

#833 rstarasov update hw_status.csv
  library/streams/2024/hw_status.csv
Labels: 1 группа

#837 Update visits_status.csv
  library/streams/2024/visits_status.csv
Labels: 1 группа

#836 Update hw_status.csv
  library/streams/2024/hw_status.csv
Labels: 1 группа

#835 agvolodina_status_hw_visit
  users/agvolodina/exercise/status/hw_status.csv
  users/agvolodina/exercise/status/visits_status.csv
Labels: 1 группа

#840 rnyunusov-hwstatus
  library/streams/2024/hw_status.csv
Labels: 1 группа
