Repository amtsu/team22, pull requests merged in 2024-02, with the labels that each got.

#423 Выполнил hw4
  users/aavolodin/exercise/hw4/volodin_hw_4.ipynb
Labels: 1 группа

#439 Сделал hw5_part_1
  users/aavolodin/exercise/hw5/hw5_part1.ipynb
Labels: 1 группа

#413 Avmorozova hw3
  exercise/hw1/home_work_1/file_1
  users/AMTsurkov/home_work_1/home_work_1.ipynb
  users/avmorozova/exercise/hw1/res2_history
  users/avmorozova/exercise/hw3/p1.ipynb
Labels: 3 группа

#441 создала новую ветку hw5_part2, со второй частью дз
  users/agvolodina/exercise/hw5/hw5_part2.ipynb
Labels: 1 группа

#477 hw5_part3
  users/agvolodina/exercise/hw5/agvolodina_hw5_part3.ipynb
Labels: 1 группа

#454 ismatrosova hw1 + hw3part1
  library/streams/2024/hw_status
  library/streams/2024/visits_status
  users/ismatrosova/exercise/hw1/home_work_1/file1
  users/ismatrosova/exercise/hw1/home_work_1/file2
  users/ismatrosova/exercise/hw1/home_work_1/file_1.txt
  users/ismatrosova/exercise/hw1/home_work_1/work_dir_new/file_1_copy.txt
  users/ismatrosova/exercise/hw1/savefile
  users/ismatrosova/exercise/hw1/theory_console_command.ipynb
  users/ismatrosova/exercise/hw3/hw-3-part-1.txt
Labels: 7 группа

#453 Kaanikin hw5
  users/kaanikin/exercise/hw5/hw-5.ipynb
Labels: 9 группа

#442 Сделал hw_5_part2
  users/aavolodin/exercise/hw5/hw_5_part2.ipynb
Labels: 1 группа

#460 JATashpulatov - hw5 (parts 1-4)
  users/jatashpulatov/exercise/hw-5/hw-5-part-1.txt
  users/jatashpulatov/exercise/hw-5/hw-5-part-2.txt
  users/jatashpulatov/exercise/hw-5/hw-5-part-3.txt
  users/jatashpulatov/exercise/hw-5/hw-5-part-4.txt
  users/jatashpulatov/exercise/hw-5/hw-5-part-5.txt
  users/jatashpulatov/exercise/hw-5/hw-5.ipynb
Labels: 3 группа

#463 Mvandreeva hw5 parts 1-4
  users/mvandreeva/study2024/exercise/hw5/hw-5.ipynb
Labels: 1 группа

#456 rstarasov HW-5. Part 1 - 4
  users/rstarasov/exercise/hw-5/hw-5-1.ipynb
  users/rstarasov/exercise/hw-5/hw-5-2.ipynb
  users/rstarasov/exercise/hw-5/hw-5-3.ipynb
  users/rstarasov/exercise/hw-5/hw-5-4.ipynb
Labels: 1 группа

#491 Arisova hw 5.4
  users/aaarisova/exercise/hw-5/hw-5-part-1.ipynb
  users/aaarisova/exercise/hw-5/hw-5-part-2.ipynb
  users/aaarisova/exercise/hw-5/hw-5-part-3.ipynb
  users/aaarisova/exercise/hw-5/hw-5-part-4.ipynb
Labels: 9 группа

#430 HW5
  users/avlotsmanov/exercise/hw5/hw-5_lotsmanov.ipynb
Labels: 8 группа

#433 okorch HW5
  users/oekorchevaya/exercise/hw-5/hw-5.ipynb
Labels: 8 группа

#495 Update hw_status
  library/streams/2024/hw_status
Labels: 2 группа

#506 MVAndreeva visit-status update
  library/streams/2024/hw_status
  library/streams/2024/visits_status
Labels: 1 группа

#505 Update visits_status
  library/streams/2024/visits_status
Labels: 8 группа

#500 Status update
  library/streams/2024/hw_status
  library/streams/2024/visits_status
Labels: 3 группа

#504 JATashpulatov - Update hw_status and visits_status
  library/streams/2024/hw_status
  library/streams/2024/visits_status
Labels: 3 группа

#496 Update hw_status
  library/streams/2024/hw_status
Labels: 2 группа

#466 Домашнее задание hw-5 + апдейт файлов учета
  users/aemareev/exercise/hw5/hw-5.ipynb
Labels: 3 группа

#493 Andvliv hw 5
  users/andvliv/exercise/hw-5/hw-5.ipynb
Labels: 2 группа

#511 Rnyunusov hw4 atmpt2
  library/streams/2024/hw_status
  users/rnyunusov/exercise/hw4/hw-4.ipynb
Labels: 1 группа

#457 Find y hw4
  users/yaauster/exercise/hw4/hw-4-result.ipynb
  users/yaauster/exercise/hw4/hw-4/hw-4.ipynb
Labels: 9 группа

#435 Find y hw3
  users/yaauster/README.md
  users/yaauster/exercise/hw1/task/theory_console_command.ipynb
  users/yaauster/exercise/hw2/task/hw-2
  users/yaauster/exercise/hw3/hw-3-part-1-result
  users/yaauster/exercise/hw3/hw-3-part-2-result.ipynb
  users/yaauster/exercise/hw3/tasks/hw-3-part-1
  users/yaauster/exercise/hw3/tasks/hw-3-part-2
Labels: 9 группа

#478 hw5_part4
  users/agvolodina/exercise/hw5/hw5_part4.ipynb
Labels: 1 группа

#485 Cделала 1-4 часть дз hw5. Знаю, что есть еще задания.
  library/streams/2024/hw_status
  users/ismatrosova/exercise/hw5/hw-5.ipynb
Labels: 7 группа

#524 Agvolodina hw5 part3
  users/agvolodina/exercise/hw5/agvolodina_hw5_part3.ipynb
Labels: 1 группа

#467 HW5 branch
  users/vvbykov/exercise/hw5/hw-5.ipynb
Labels: 3 группа

#520 Выпоненное ДЗ 4
  users/eanabatov/exercise/hw-4/hw-4.ipynb
Labels: 3 группа

#525 saivanov обновил hw_status и visits_status
  library/streams/2024/hw_status
  library/streams/2024/visits_status
Labels: 9 группа

#488 Aavolodin hw5 part3
  users/aavolodin/exercise/hw5/hw5_part3.ipynb
Labels: 1 группа

#523 Сделал 4 часть hw5
  users/aavolodin/exercise/hw5/hw5_part4.ipynb
Labels: 1 группа

#528 Ismatrosova Выполнила hw 6
  library/streams/2024/hw_status
  users/ismatrosova/exercise/hw6/Git-homework.txt
  users/ismatrosova/exercise/hw6/hw-6.ipynb
  users/ismatrosova/exercise/hw6/hw6.pdf
Labels: 7 группа

#526 Kaanikin hw5
  users/kaanikin/exercise/hw5/hw-5.ipynb
Labels: 9 группа

#530 Aemareev hw6 algorithms
  users/aemareev/exercise/hw6/hw6-algorithms.ipynb
Labels: 3 группа
